# After any change to this file you MUST re-sign and checkin the .drone.yml.sig
# When you are ready to submit a pull request, you must regenerate .drone.yml.sig for the vmware/vic repo:
# $ export DRONE_SERVER=https://ci.vcna.io
# $ export DRONE_TOKEN=<token>
# $ drone sign vmware/vic-ui
# The secrets file is in our local git repo.  Ask mhagen for access.

---
workspace:
  base: /go
  path: src/github.com/vmware/vic-ui

pipeline:
  clone:
    image: plugins/git
    tags: true
    # dont clone submodules
    recursive: false

  vic-ui:
    image: harbor.ci.drone.local/library/vic-integration-test:1.36
    pull: true
    environment:
      BUILD_NUMBER: ${DRONE_BUILD_NUMBER}
      BIN: bin
      GS_PROJECT_ID: ${GS_PROJECT_ID}
      GS_CLIENT_EMAIL: ${GS_CLIENT_EMAIL}
      GS_PRIVATE_KEY: ${GS_PRIVATE_KEY}
    commands:
      - make vic-ui-plugins
    when:
      repo: vmware/vic-ui
      branch: [ master, releases/*, refs/tags/* ]

  bundle:
    image: harbor.ci.drone.local/library/golang:1.8
    pull: true
    environment:
      BIN: bin
      BIN_TEMP_DIR: bin/ci
      GOPATH: /go
      SHELL: /bin/bash
    commands:
      - rm -rf $BIN_TEMP_DIR
      - mkdir -p $BIN_TEMP_DIR/ui
      - cp -rf bin/ui/* $BIN_TEMP_DIR/ui
      - tar -czvf vic_ui_${DRONE_BUILD_NUMBER}.tar.gz $BIN_TEMP_DIR/ui
      - mkdir bundle
      - cp $BIN/vic_ui_${DRONE_BUILD_NUMBER}.tar.gz bundle
    when:
      repo: vmware/vic-ui
    # event: [ push, tag ]
    # branch: [ master, releases/*, refs/tags/* ]

  publish-gcs-builds-on-pass:
    image: maplain/drone-gcs:latest
    pull: true
    source: bundle
    target: vic-ui-builds
    acl:
      - allUsers:READER
    cache_control: public,max-age=3600
    when:
      repo: vmware/vic-ui
    # event: [ push ]
    # branch: [ master, releases/*, refs/tags/* ]
      status: success
