workspace:
  base: /go
  path: src/github.com/vmware/vic

pipeline:
  clone:
    image: plugins/git
    tags: true
    recursive: false
  vic-uia:
    image: ${TEST_BUILD_IMAGE=gcr.io/eminent-nation-87317/vic-integration-test:1.33}
    pull: true
    environment:
      BIN: bin
      GOPATH: /go
      SHELL: /bin/bash
      NIMBUS_USER: ${NIMBUS_USER}
      NIMBUS_PASSWORD: ${NIMBUS_PASSWORD}
      NIMBUS_GW: ${NIMBUS_GW}
      TEST_DATASTORE: ${TEST_DATASTORE}
      TEST_RESOURCE: ${TEST_RESOURCE}
      GOVC_INSECURE: true
      BUILD_NUMBER: ${buildNumber}
      TEST_VSPHERE_VER: #TEST_VSPHERE_VER
      TEST_OS: #TEST_OS
      SELENIUM_BROWSER: #SELENIUM_BROWSER
      BROWSER_NORMALIZED_NAME: #BROWSER_NORMALIZED_NAME
      UI_TEST_CASES_FOLDER: tests/manual-test-cases/Group18-VIC-UI
      TEST_RESULTS_FOLDER: #TEST_RESULTS_FOLDER
    commands:
      - apt-get update && apt-get install -yq maven netcat
      - pip install pexpect robotframework-selenium2library
      - cd $UI_TEST_CASES_FOLDER
      - robot -C ansi -d ../../../$TEST_RESULTS_FOLDER 18-4-VIC-UI-Plugin-tests.robot
