workspace:

  base: /go
  path: src/github.com/vmware/vic-ui
pipeline:

  clone:
    image: plugins/git
    tags: true
    recursive: false

  check-org-membership:
    image: 'wdc-harbor-ci.eng.vmware.com/default-project/vic-integration-test:1.44'
    pull: true
    environment:
      BIN: bin
      GOPATH: /go
      SHELL: /bin/bash
    secrets:
      - github_automation_api_key
    commands:
      - echo ${DRONE_COMMIT_AUTHOR}
      - /bin/bash -c '[[ ! $(curl --silent "https://api.github.com/orgs/vmware/members/${DRONE_COMMIT_AUTHOR}?access_token=$GITHUB_AUTOMATION_API_KEY") ]]'
    when:
      status: success

  vic-ui:
    image: 'gcr.io/eminent-nation-87317/vic-integration-test:1.36'
    pull: true
    environment:
      BIN: bin
    secrets:
      - gs_client_email
      - gs_private_key
      - gs_project_id
    commands:
      - 'export BUILD_NUMBER=${DRONE_BUILD_NUMBER}'
      - 'make vic-ui-plugins'
    when:
      repo: vmware/vic-ui
      branch: [master, 'releases/*', 'refs/tags/*']

  bundle:
    image: 'gcr.io/eminent-nation-87317/vic-integration-test:1.36'
    pull: true
    environment:
      BIN: bin
      GOPATH: /go
      SHELL: /bin/bash
    commands:
      - 'mkdir -p $BIN/ui'
      - 'tar -czvf $BIN/vic_ui_${DRONE_BUILD_NUMBER}.tar.gz $BIN/ui'
      - 'mkdir bundle'
      - 'mkdir bundle-release'
      - 'cp $BIN/vic_ui_${DRONE_BUILD_NUMBER}.tar.gz bundle'
      - 'cp $BIN/vic_ui_${DRONE_BUILD_NUMBER}.tar.gz bundle-release/vic_ui_`git describe --tags $(git rev-list --tags --max-count=1)`.tar.gz'
      - 'rm -rf $BIN'
      - 'ls -la bundle'
    when:
      repo: vmware/vic-ui
      event: [push, tag]
      branch: [master, 'releases/*', 'refs/tags/*']

  publish-gcs-builds-on-pass:
    image: 'maplain/drone-gcs:latest'
    pull: true
    secrets:
      - google_key
    source: bundle
    target: vic-ui-builds
    acl:
      - 'allUsers:READER'
    cache_control: 'public,max-age=3600'
    when:
      repo: vmware/vic-ui
      event: [push]
      branch: [master, 'releases/*']
      status: success

  publish-gcs-releases:
    image: 'maplain/drone-gcs:latest'
    pull: true
    secrets:
      - google_key
    source: bundle-release
    target: vic-ui-releases
    acl:
      - 'allUsers:READER'
    cache_control: 'public,max-age=3600'
    when:
      repo: vmware/vic-ui
      event: [push, tag]
      branch: ['refs/tags/*']
      status: success

  report-coverage:
    image: 'robertstettner/drone-codecov'
    secrets:
      - codecov_token
    files:
      - 'h5c/vic/src/vic-webapp/coverage/lcov.info'

  pass-rate:
    image: 'gcr.io/eminent-nation-87317/vic-integration-test:1.42'
    pull: true
    environment:
      BIN: bin
      SHELL: /bin/bash
    secrets:
      - github_automation_api_key
      - slack_url
    commands:
      - tests/pass-rate.sh

services:
  selenium:
    image: selenium/standalone-firefox
