#!/usr/bin/env node

/**
 * Module dependencies.
 */

var app = require('./app');
var debug = require('debug')('server:server');
var http = require('http');
var https = require('https');
var fs = require('fs');
const key = fs.readFileSync(process.env['TLS_PRIVATE_KEY']);
const cert = fs.readFileSync(process.env['TLS_CERTIFICATE']);
const HTTP_PORT = process.env['PORT'];
const TLS_PORT = process.env['TLS_PORT'];

/**
 * Get port from environment and store in Express.
 */

const port = normalizePort(TLS_PORT);
const http_port = normalizePort(HTTP_PORT);

app.set('port', port);

// Create HTTP server for redirect
http.createServer((req, res) => {
  res.writeHead(301, {
    "Location": "https://" + req.headers.host.replace(`:${HTTP_PORT}`, `:${TLS_PORT}`) + req.url
  });
  res.end();
}).listen(http_port);

/**
 * Create HTTPS server.
 */

var server = https.createServer({
  key: key,
  cert: cert
}, app);

/**
 * Listen on provided port, on all network interfaces.
 */

server.listen(port);
server.on('error', onError);
server.on('listening', onListening);

/**
 * Normalize a port into a number, string, or false.
 */

function normalizePort(val) {
  var port = parseInt(val, 10);

  if (isNaN(port)) {
    // named pipe
    return val;
  }

  if (port >= 0) {
    // port number
    return port;
  }

  return false;
}

/**
 * Event listener for HTTPS server "error" event.
 */

function onError(error) {
  if (error.syscall !== 'listen') {
    throw error;
  }

  var bind = typeof port === 'string'
    ? 'Pipe ' + port
    : 'Port ' + port;

  // handle specific listen errors with friendly messages
  switch (error.code) {
    case 'EACCES':
      console.error(bind + ' requires elevated privileges');
      process.exit(1);
      break;
    case 'EADDRINUSE':
      console.error(bind + ' is already in use');
      process.exit(1);
      break;
    default:
      throw error;
  }
}

/**
 * Event listener for HTTPS server "listening" event.
 */

function onListening() {
  var addr = server.address();
  var bind = typeof addr === 'string'
    ? 'pipe ' + addr
    : 'port ' + addr.port;
  debug('Listening on ' + bind);
}
