#!/usr/bin/env node

/*
 Copyright 2018 VMware, Inc. All Rights Reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/

const app = require('./app');
const debug = require('debug')('server:server');
const http = require('http');
const https = require('https');
const fs = require('fs');
const key = fs.readFileSync(process.env['TLS_PRIVATE_KEY']);
const cert = fs.readFileSync(process.env['TLS_CERTIFICATE']);
const HTTP_PORT = process.env['PORT'];
const TLS_PORT = process.env['TLS_PORT'];

const port = normalizePort(TLS_PORT);
const http_port = normalizePort(HTTP_PORT);

app.set('port', port);

// Create HTTP server for redirect
http.createServer((req, res) => {
  res.writeHead(301, {
    "Location": "https://" + req.headers.host.replace(`:${HTTP_PORT}`, `:${TLS_PORT}`) + req.url
  });
  res.end();
}).listen(http_port);

/**
 * Create HTTPS server.
 */

var server = https.createServer({
  key: key,
  cert: cert
}, app);

/**
 * Listen on provided port, on all network interfaces.
 */

server.listen(port);
server.on('error', onError);
server.on('listening', onListening);

/**
 * Normalize a port into a number, string, or false.
 */

function normalizePort(val) {
  var port = parseInt(val, 10);

  if (isNaN(port)) {
    // named pipe
    return val;
  }

  if (port >= 0) {
    // port number
    return port;
  }

  return false;
}

/**
 * Event listener for HTTPS server "error" event.
 */

function onError(error) {
  if (error.syscall !== 'listen') {
    throw error;
  }

  var bind = typeof port === 'string'
    ? 'Pipe ' + port
    : 'Port ' + port;

  // handle specific listen errors with friendly messages
  switch (error.code) {
    case 'EACCES':
      console.error(bind + ' requires elevated privileges');
      process.exit(1);
      break;
    case 'EADDRINUSE':
      console.error(bind + ' is already in use');
      process.exit(1);
      break;
    default:
      throw error;
  }
}

/**
 * Event listener for HTTPS server "listening" event.
 */

function onListening() {
  var addr = server.address();
  var bind = typeof addr === 'string'
    ? 'pipe ' + addr
    : 'port ' + addr.port;
  debug('Listening on ' + bind);
}
